services:
  - name: collection-app-server
    type: web
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_HOST
        value: localhost
      - key: DATABASE_USER
        value: root
      - key: DATABASE_PASSWORD
        value: 
      - key: DATABASE_NAME
        value: CollectionApp
      - key: PORT
        value: 3306
    plan: free
